### ISSUE TITLE
API rate limit exceeded for 52.0.240.122. 

### ISSUE THREAD

**Issue by sanemat** [packsaddle/ruby-saddler#36]
https://github.com/jser/jser.github.io/pull/158
https://travis-ci.org/jser/jser.github.io/builds/80978812

```
E, [2015-09-18T08:56:46.240274 #2389] ERROR -- Saddler: options
E, [2015-09-18T08:56:46.240480 #2389] ERROR -- Saddler: {"options"=>{}, "debug"=>false, "verbose"=>false, "require"=>"saddler/reporter/github", "reporter"=>"Saddler::Reporter::Github::PullRequestReviewComment"}
E, [2015-09-18T08:56:46.240613 #2389] ERROR -- Saddler: input data
E, [2015-09-18T08:56:46.240710 #2389] ERROR -- Saddler: <?xml version='1.0' encoding='UTF-8'?><checkstyle version='4.3'><file name='/home/travis/build/jser/jser.github.io/_i18n/ja/_posts/2015/2015-09-16-react-0.14-eslint-1.4-es5.md'/></checkstyle>
E, [2015-09-18T08:56:46.240834 #2389] ERROR -- Saddler: reporter
E, [2015-09-18T08:56:46.240927 #2389] ERROR -- Saddler: #<Saddler::Reporter::Github::PullRequestReviewComment:0x000000014395d0 @output=#<IO:<STDOUT>>>
/home/travis/.rvm/gems/ruby-2.2.0/gems/octokit-4.1.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/jser/jser.github.io/pulls/158/comments: 403 - API rate limit exceeded for 52.0.240.122. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting (Octokit::TooManyRequests)
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/octokit-4.1.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/octokit-4.1.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/sawyer-0.6.0/lib/sawyer/agent.rb:94:in `call'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/octokit-4.1.0/lib/octokit/connection.rb:154:in `request'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/octokit-4.1.0/lib/octokit/connection.rb:84:in `paginate'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/octokit-4.1.0/lib/octokit/client/pull_requests.rb:172:in `pull_request_comments'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/saddler-reporter-github-0.1.4/lib/saddler/reporter/github/client.rb:39:in `pull_request_review_comments'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/saddler-reporter-github-0.1.4/lib/saddler/reporter/github/pull_request_review_comment.rb:16:in `report'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/saddler-0.1.1/lib/saddler/cli.rb:37:in `report'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/saddler-0.1.1/exe/saddler:5:in `<top (required)>'
    from /home/travis/.rvm/gems/ruby-2.2.0/bin/saddler:23:in `load'
    from /home/travis/.rvm/gems/ruby-2.2.0/bin/saddler:23:in `<main>'
    from /home/travis/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
    from /home/travis/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
The command "sh test/travis-spellcheck.sh" exited with 1.
```

**Comment by sanemat** [comment]
I don't reproduce this. I think travis-ci lost encrypted value temporary.
