### ISSUE TITLE
Diff and error exists, but not found error in github

### ISSUE THREAD

**Issue by sanemat** [packsaddle/ruby-saddler#37]
https://travis-ci.org/packsaddle/example-travis_ci-commit/jobs/81002675
https://github.com/packsaddle/example-travis_ci-commit/pull/1

```
E, [2015-09-18T12:04:23.079527 #2026] ERROR -- Saddler: options
E, [2015-09-18T12:04:23.079644 #2026] ERROR -- Saddler: {"options"=>{}, "debug"=>false, "verbose"=>false, "require"=>"saddler/reporter/github", "reporter"=>"Saddler::Reporter::Github::PullRequestReviewComment"}
E, [2015-09-18T12:04:23.079717 #2026] ERROR -- Saddler: input data
E, [2015-09-18T12:04:23.079774 #2026] ERROR -- Saddler: <?xml version='1.0'?>
<checkstyle>
  <file name='lib/example/travis_ci.rb'>
    <error column='120' line='7' message='Line is too long. [164/120]' severity='info' source='com.puppycrawl.tools.checkstyle.Metrics/LineLength'/>
  </file>
</checkstyle>
E, [2015-09-18T12:04:23.079857 #2026] ERROR -- Saddler: reporter
E, [2015-09-18T12:04:23.079913 #2026] ERROR -- Saddler: #<Saddler::Reporter::Github::PullRequestReviewComment:0x00000001c78ed0 @output=#<IO:<STDOUT>>>
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.1.0/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/packsaddle/example-travis_ci-commit/pulls/1/comments: 404 - Not Found // See: https://developer.github.com/v3/pulls/comments/#create-a-comment (Octokit::NotFound)
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.1.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.1.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/sawyer-0.6.0/lib/sawyer/agent.rb:94:in `call'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.1.0/lib/octokit/connection.rb:154:in `request'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.1.0/lib/octokit/connection.rb:28:in `post'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.1.0/lib/octokit/client/pull_requests.rb:211:in `create_pull_request_comment'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/saddler-reporter-github-0.1.4/lib/saddler/reporter/github/client.rb:53:in `create_pull_request_review_comment'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/saddler-reporter-github-0.1.4/lib/saddler/reporter/github/pull_request_review_comment.rb:29:in `block in report'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/saddler-reporter-github-0.1.4/lib/saddler/reporter/github/pull_request_review_comment.rb:28:in `each'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/saddler-reporter-github-0.1.4/lib/saddler/reporter/github/pull_request_review_comment.rb:28:in `report'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/saddler-0.1.1/lib/saddler/cli.rb:37:in `report'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/saddler-0.1.1/exe/saddler:5:in `<top (required)>'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/saddler:23:in `load'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/saddler:23:in `<main>'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by sanemat** [comment]
I don't reproduce this. I think travis-ci lost encrypted value temporary.
