### ISSUE TITLE
fatal: Not a valid object name  (Git::GitExecuteError) on Jenkins

### ISSUE THREAD

**Issue by yshrsmz** [packsaddle/ruby-saddler#44]
Hi, thanks for this great tool.
I got an error below on my Jenkins(with GitHub pull request builder plugin, and reporter is PullRequestReviewComment)

```
E, [2016-05-12T17:39:45.412533 #44380] ERROR -- Saddler: reporter
E, [2016-05-12T17:39:45.412593 #44380] ERROR -- Saddler: #<Saddler::Reporter::Github::PullRequestReviewComment:0x007f97fcb016c0 @output=#<IO:<STDOUT>>>
/Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/git-1.3.0/lib/git/lib.rb:937:in `command': git '--git-dir=/Users/myuser/.jenkins/jobs/liverpool-android-pull-request/workspace/.git' '--work-tree=/Users/myuser/.jenkins/jobs/liverpool-android-pull-request/workspace' cat-file '-t' ''  2>&1:fatal: Not a valid object name  (Git::GitExecuteError)
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/git-1.3.0/lib/git/lib.rb:166:in `object_type'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/git-1.3.0/lib/git/object.rb:301:in `new'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/git-1.3.0/lib/git/base/factory.rb:53:in `object'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/saddler-reporter-support-git-1.0.0/lib/saddler/reporter/support/git/repository.rb:72:in `tracking'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/saddler-reporter-support-git-1.0.0/lib/saddler/reporter/support/git/repository.rb:64:in `block in merging_object'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/saddler-reporter-support-git-1.0.0/lib/saddler/reporter/support/git/repository.rb:63:in `select'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/saddler-reporter-support-git-1.0.0/lib/saddler/reporter/support/git/repository.rb:63:in `merging_object'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/saddler-reporter-support-git-1.0.0/lib/saddler/reporter/support/git/repository.rb:52:in `merging_sha'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/saddler-reporter-github-1.0.0/lib/saddler/reporter/github/client.rb:69:in `block in pull_request_patches'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/saddler-reporter-github-1.0.0/lib/saddler/reporter/github/client.rb:68:in `each'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/saddler-reporter-github-1.0.0/lib/saddler/reporter/github/client.rb:68:in `pull_request_patches'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/saddler-reporter-github-1.0.0/lib/saddler/reporter/github/pull_request_review_comment.rb:23:in `report'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/saddler-1.0.0/lib/saddler/cli.rb:37:in `report'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/saddler-1.0.0/exe/saddler:5:in `<top (required)>'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/bin/saddler:23:in `load'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/bin/saddler:23:in `<main>'
```

after digging it for a while, it seems like target branch name was unseeable from saddler.
but when I run `echo $ghprbTargetBranch`, it prints `master`

any idea how to solve this?

**Comment by sanemat** [comment]
Thanks for your reporting!
And this is a good question!

> any idea how to solve this?

Short answer: `NO IDEA (now).` 😢 

Long answer:
I am sorry for the inconvenience.
I'm trying to solve this issue. This is `saddler-reporter-support-git`'s issue. 
- [Raise error if there is no tracking_branch #38](https://github.com/packsaddle/ruby-saddler-reporter-support-git/issues/38)
- [Consider invalid object name #39](https://github.com/packsaddle/ruby-saddler-reporter-support-git/issues/39)

I'll release `saddler-reporter-support-git` `v2.0.0`, and I hope this works fine.
I'll release this in a few days. I wish. I hope. 🎅

**Comment by sanemat** [comment]
Before fix this, would you use `Saddler::Reporter::Github::PullRequestComment` instead of `PullRequestReviewComment`?

**Comment by yshrsmz** [comment]
Thanks for the response!
looking forward to seeing the update!
I'm going to use `Saddler::Reporter::Github::PullRequestComment` for now, which seems working :)

**Comment by sanemat** [comment]
I ship `saddler-reporter-support-git` [v2.0.0](https://github.com/packsaddle/ruby-saddler-reporter-support-git/releases/tag/v2.0.0), and it works fine with `GitHub pull request builder plugin`. Please try it!

**Comment by yshrsmz** [comment]
Thanks, I tried v2.0.0, and got following error:

```
E, [2016-05-15T11:26:17.345644 #12599] ERROR -- Saddler: reporter
E, [2016-05-15T11:26:17.345693 #12599] ERROR -- Saddler: #<Saddler::Reporter::Github::PullRequestReviewComment:0x007ffc73b3ab88 @output=#<IO:<STDOUT>>>
/Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/octokit-4.3.0/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/myuser/saampleapp/pulls/3537/comments: 422 - Validation Failed (Octokit::UnprocessableEntity)
Error summary:
  resource: PullRequestReviewComment
  code: custom
  field: commit_id
  message: commit_id is not part of the pull request // See: https://developer.github.com/v3/pulls/comments/#create-a-comment
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/sawyer-0.7.0/lib/sawyer/agent.rb:94:in `call'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/octokit-4.3.0/lib/octokit/connection.rb:154:in `request'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/octokit-4.3.0/lib/octokit/connection.rb:28:in `post'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/octokit-4.3.0/lib/octokit/client/pull_requests.rb:211:in `create_pull_request_comment'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/saddler-reporter-github-1.0.0/lib/saddler/reporter/github/client.rb:80:in `create_pull_request_review_comment'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/saddler-reporter-github-1.0.0/lib/saddler/reporter/github/pull_request_review_comment.rb:34:in `block in report'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/saddler-reporter-github-1.0.0/lib/saddler/reporter/github/pull_request_review_comment.rb:33:in `each'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/saddler-reporter-github-1.0.0/lib/saddler/reporter/github/pull_request_review_comment.rb:33:in `report'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/saddler-1.0.0/lib/saddler/cli.rb:37:in `report'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/saddler-1.0.0/exe/saddler:5:in `<top (required)>'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/bin/saddler:23:in `load'
    from /Users/myuser/.rbenv/versions/2.0.0-p247/bin/saddler:23:in `<main>'
```

will look into it more deeper tomorrow.
should I open a new issue?

**Comment by sanemat** [comment]
@yshrsmz :cry:  Please open a new issue.
